### ISSUE TITLE
How simple would it be for a somewhat tech-aware beginner to mod this with a third encoder?

### ISSUE THREAD

**Issue by arrowtype** [joshajohnson/Hub20#2]
Hi Josh, this is an incredibly cool project! It’s _so_ close to being my dream numpad, but I would love to find (or make?) something with _three_ encoders.

I’m a total noob in this area, but very curious how big a challenge it might be to learn the requisite software & processes to add a third encoder to the system.

My main reason for seeking three encoders is the software I use to kern fonts. It would be amazing to use one encoder to step through a list of letter pairs, a second to make large-grained adjustments, and a third to make fine-grained adjustments. I’ve tried to process with a two-encoder board, and it’s very nice, but I wish I didn’t have to toggle modes to go from large to small adjustments.

Thanks for making and sharing this project!

(PS: Apologies if this is the wrong place to ask, but I figure at least others might come across it if they search for a similar question.)

**Comment by joshajohnson** [comment]
Hey Stephen,

Adding a third encoder would be easy if it wasn't for the USB hub being in the way.

The below image shows the two encoders on either side of the PCB, with the USB hub and associated hardware in the middle.

If you were willing to remove the USB hub, or change the mechanical dimensions of the board it would be feasible to add a third encoder, but doing that whilst keeping the same form factor would be very challenging if not impossible.

![image](https://user-images.githubusercontent.com/29656613/165760210-90d6889f-985f-4a7e-bf29-01730b3b7cc9.png)

Another issue is that both the micro controller and USB hub used on this board are near impossible to purchase due to supply shortages these days, so you'd want to order the parts before going to the effort of redesigning the PCB.

As you can probably guess from the above I wouldn't recommend going down this path, but if you want to give it a go / or design a dedicated board with just three encoders and a pro micro or similar controller feel free to give me a yell if I can lend a hand.

Cheers

**Comment by arrowtype** [comment]
This is amazing; thank you so much for the insights, Josh!

I do think I'd be willing to give up the usb hub in favor of a third encoder, but I hadn't considered the (obvious, in hindsight) issue of supply constraints. So, I'll look to solve that issue, and maybe once I can get those, I'll try my hand at KiCad. I may indeed give a shout if I reach that stage. (And if you ever need font/typographic insights, I'd be happy to reciprocate!)

Cheers!
